name: Update boringssl
on:
  push:
    branches: [ master ]

  schedule:
    - cron: '0 */2 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: update boringssl
        uses: actions/checkout@v2
        with:
          repository: google/boringssl
          path: build/boringssl
